services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-nodejs-app
    container_name: nodejs-container
    ports:
      - "192.168.1.180:80:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
