version: '3.8'

services:
  app:
    image: node:16
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"